// current weather
export const CURRENT_WEATHER_REQUESTED = 'CURRENT_WEATHER_REQUESTED';
export const CURRENT_WEATHER_SUCCEEDED = 'CURRENT_WEATHER_SUCCEEDED';
export const CURRENT_WEATHER_FAILED = 'CURRENT_WEATHER_FAILED';
