// current weather
export const CURRENT_WEATHER_REQUESTED = 'CURRENT_WEATHER_REQUESTED';
export const CURRENT_WEATHER_SUCCEEDED = 'CURRENT_WEATHER_SUCCEEDED';
export const CURRENT_WEATHER_FAILED = 'CURRENT_WEATHER_FAILED';

// weather forcast
export const WEATHER_FORECAST_REQUESTED = 'WEATHER_FORECAST_REQUESTED';
export const WEATHER_FORECAST_SUCCEEDED = 'WEATHER_FORECAST_SUCCEEDED';
export const WEATHER_FORECAST_FAILED = 'WEATHER_FORECAST_FAILED';
